apiVersion: apps/v1
kind: Deployment
metadata:
  name: current-time-api
  namespace: current-time-api  # ✅ Change this from "argocd" to your app namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: current-time-api
  template:
    metadata:
      labels:
        app: current-time-api
    spec:
      containers:
        - name: current-time-api
          image: collinskiprotich780/current-time-api:latest  # ✅ Ensure this is correct
          ports:
            - containerPort: 3000
          resources:   # ✅ Add resource requests and limits
            limits:
              cpu: "500m"     # Max CPU usage (0.5 CPU core)
              memory: "256Mi" # Max Memory usage (256 MB)
            requests:
              cpu: "250m"     # Guaranteed CPU (0.25 CPU core)
              memory: "128Mi" # Guaranteed Memory (128 MB)
