apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-workflows
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-minikube
  template:
    metadata:
      labels:
        app: hello-minikube
    spec:
      containers:
      - name: hello-minikube
        image: nginx  # Change this to your app image
        ports:
        - containerPort: 80
