apiVersion: v1
kind: Service
metadata:
  name: current-time-api-service
  namespace: current-time-api
spec:
  selector:
    app: current-time-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30081
  type: NodePort

