name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Or any other runner you want to use
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Removed the 'Set up Node.js' step since you already have Node.js and npm on the machine

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -f docker/Dockerfile -t collinskiprotich780/current-time-api:${{ github.sha }} .
          docker tag collinskiprotich780/current-time-api:${{ github.sha }} collinskiprotich780/current-time-api:latest
          docker push collinskiprotich780/current-time-api:${{ github.sha }}
          docker push collinskiprotich780/current-time-api:latest
